### ISSUE TITLE
Cannot build PiWind keys server

### ISSUE THREAD

**Issue by rtahiry** [OasisLMF/OasisPiWind#11]
Hello, 

I am trying to build and run the PiWind model by following the steps given in the documentation. However, I cannot seem to build the keys server docker image.

```
Sending build context to Docker daemon  9.212MB
Step 1/24 : FROM coreoasis/oasis_base:latest
pull access denied for coreoasis/oasis_base, repository does not exist or may require 'docker login'
```

I assume that I need to build/get the coreoasis/oasis_base:latest image first but I have no idea regarding how to build or get that. Is there any link to a documentation that would solve this issue?

Cheers,
Tahiry

OS: ubuntu 17.20
Docker: 17.12.1

Edit:
I cannot find the coreoasis/oasis_base repo [here](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=coreoasis&starCount=0).

**Comment by sr-murthy** [comment]
The PiWind keys server Docker file was recently updated to source a base image that is published a private OasisLMF DockerHub repository `coreoasis/oasis_base`. You don't have read access to this repository, which is why you cannot access the image during the build.

Given that PiWind is meant to be a public demonstration model the keys server image shouldn't be sourcing a private image. I will update the Docker file in the repository today, so please try the build again.

**Comment by sr-murthy** [comment]
@rtahiry Please update your local PiWind repository from the remote (`git pull origin master`), and try the build again.
