### ISSUE TITLE
Output losses divided on Coverage Type

### ISSUE THREAD

**Issue by shivamspj** [OasisLMF/OasisPiWind#22]
Can we have losses on Coverage Types? Like one loss for Business Interruption and other for Content of Building and Business Interruption?

**Comment by mpinkerton-oasis** [comment]
Yes, we can support other coverage types in models. We are intending to extend the PiWind example to illustrate this at some point.

May I ask what your goals are/what organize you are from? It might be more useful to set up a Slack channel for discussions rather than creating GitHub issues.

**Comment by shivamspj** [comment]
I am a research associate in NIT Bhopal India. I am trying to do few calculation as my dissertation project. 
I am getting help from some organization also which I am not allowed to disclose without their consent.

So, can we get this aggregated loss on coverage type in MDK or Flamingo?

Also can we set up a channel for discussion?

**Comment by shivamspj** [comment]
We are from Xceedance Consulting Pvt. Ltd. India. We can sure set up a Slack channel. 

Please let us if we can generate losses aggregated on Coverage types through MDK? or Flamingo setup?

**Comment by sr-murthy** [comment]
@shivamspj PiWind is a demonstration windstorm model which currently supports only buildings coverage type for the lookup. We can extend this as appropriate, but I think what you are looking for may be your own model customised to your requirements. You can use PiWind as a template. PiWind uses an automated built-in lookup framework (for the peril and vulnerability lookups) that is provided by the MDK, and this is driven by a configuration JSON file

https://github.com/OasisLMF/OasisPiWind/blob/develop/keys_data/PiWind/lookup.json

My recommendation for you would be to create a template Oasis model repository using 

https://github.com/OasisLMF/cookiecutter-OasisModel

and then get starting on adding and defining the assets required to run your model. I can do this at my end, so that the repository is managed via the OasisLMF GitHub organizational user, and you will have full access.

If a built-in lookup is appropriate for your model then I can help with that. You also have the option of writing your own custom lookup. Either will work. I have created a private Slack channel for discussions. Please provide a list of email addresses of members from your organization who will need access to this. We can also add a webhook for your repository to post updates to a separate private GitHub channel.

**Comment by shivamspj** [comment]
Please add 
1. ramesh.banagar@xceedance.com
2. kumar.shivam@xceedance.com
3. shivam.huriya@xceedance.com
4. asmita.sharma@xceedance.com
5. puneet.bajpai@xceedance.com

**Comment by shivamspj** [comment]
Thanks a lot for your reply and enlightening us on Oasis.

**Comment by sr-murthy** [comment]
Invites sent to Slack channel - please check for invite emails. On acceptance you will join the general workspace we have for external organizations, but if you post in the general channel I can then add you to the Xceedance private discussion channel. Note: as I mentioned before it seems what you want is to customise your own model (or models). The first step is to create an Oasis compatible model repository using 

https://github.com/OasisLMF/cookiecutter-OasisModel

We can guide you through that. Once you have the repository, then you can define your model and its assets, including the lookup data and configuration.

**Comment by sr-murthy** [comment]
Please move all discussions to the Slack channel. Closing.
